services:
  db:
    image: postgres:16
    container_name: nakama_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nakama
    ports:
      - "5434:5432"
    volumes:
      - nakama_postgres_data:/var/lib/postgresql/data

volumes:
  nakama_postgres_data:
